name: Serious Sound
favicon: null
layout_spectrum: 0.37213
typography_spectrum: 0.11945
title: Serious Sound Ent.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#94969a'
    - '#b20305'
    - '#e3e5e6'
    - '#ca3e42'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
