name: SeriousSound
favicon: null
layout_spectrum: 0.8274218083824962
typography_spectrum: 0.31456791679374874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.743287940742448
  lightness: 0.5355155700817704
  saturation: 0.39935148507356644
  rhythmicContrast: 0.20730127790011466
purpose: []
