name: SeriousSound
favicon: null
layout_spectrum: 0.8274218083824962
typography_spectrum: 0.31456791679374874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#94969a'
    - '#b20305'
    - '#e3e5e6'
    - '#ca3e42'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
